### ISSUE TITLE
非常期待这个项目，会不会考虑改成静态库的方式

### ISSUE THREAD

**Issue by enp6** [WangHoi/kwui-rs#2]
非常期待这个项目，会不会考虑将kwui.dll改成lib静态库的方式？
工具单文件落地这也更加符合小型用户界面库的定位~

**Comment by WangHoi** [comment]
static-crt支持的，但是用不了预编译版本的kwui-rs，得从源码构建：

1. 检出kwui-rs 与submodule
2. 修改您的项目的 Cargo.toml，指向源码：
```toml
[patch.crates-io]
kwui = { path = "{cloned_kwui_dir}" }
kwui-sys = { path = "{cloned_kwui_dir}/kwui-sys" }
kwui-cli = { path = "{cloned_kwui_dir}/kwui-cli" }
```
3. 在您的项目的 .cargo/config.toml，做如下修改：
```toml
[build]
rustflags = ["-C", "target-feature=+crt-static"]
```
